### PR TITLE
Add automated testing on Travis CI

### PR DESCRIPTION
**Pull request by cclauss**
Test results: https://travis-ci.com/cclauss/bsed

The owner of the this repo would need to go to https://travis-ci.com/profile, log in with GitHub credentials, select the __free plan__, and flip the repository switch on to enable free automated testing of all pull requests.  Travis will lint with flake8 and then run __python runtests__.

Add [flake8](http://flake8.pycqa.org) tests to find Python syntax errors and undefined names.

__E901,E999,F821,F822,F823__ are the "_showstopper_" flake8 issues that can halt the runtime with a SyntaxError, NameError, etc. Most other flake8 issues are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

### CODE REVIEW

**Comment by andrewbihl** [comment]
Thank you @cclauss for the recommendation. I'll leave this issue open until I get around to this.

**Comment by cclauss** [comment]
👍 https://travis-ci.com/andrewbihl

**Comment by jayvdb** [comment]
ping @cclauss

**Comment by cclauss** [comment]
Yes @jayvdb, how can I help?

**Comment by jayvdb** [comment]
Apologies, I should have pingged @andrewbihl to see if we can get this merged.

**Review by jayvdb — APPROVED** [review]

**Pull request closed without merging**
